#!/usr/bin/env python3
"""Deterministic interoperability workspace, manifest, and reconstruction helpers.

Shared by ``prepare_imod_to_warp.py`` / ``export_warp_to_imod.py`` /
``validate_interoperability.py``. The workspace is condition- and
refinement-model-aware, rerun-safe, and collision-free. Source data is never
modified: command files are copied to ``*.original.*`` and patched copies are
written under distinct ``*.missalign.*`` names; large stacks are individually
symlinked, never whole directories.
"""
from __future__ import annotations

import hashlib
import json
import os
import shlex
import sys
from pathlib import Path
from typing import Any

WORKSPACE_SUBDIRS = [
    "source/metadata", "source/links",
    "imod/input", "imod/generated", "imod/command_files", "imod/reports",
    "warp/staging", "warp/tiltstacks", "warp/metadata", "warp/reports",
    "missalignment/configs", "missalignment/results", "missalignment/manifests", "missalignment/logs",
    "export/residual_xf", "export/composed_xf", "export/reconstruction_inputs", "export/reports",
    "scripts",
    "validation/synthetic", "validation/imod_reference", "validation/warp_reference",
    "validation/roundtrip", "validation/reports",
    "provenance",
]


def workspace_root(out_dir: Path) -> Path:
    return Path(out_dir).resolve() / "interoperability"


def create_workspace(out_dir: Path) -> Path:
    root = workspace_root(out_dir)
    for sub in WORKSPACE_SUBDIRS:
        (root / sub).mkdir(parents=True, exist_ok=True)
    return root


def result_dir(out_dir: Path, condition: str, refinement_model: str, profile: str = "standard") -> Path:
    """Collision-free, condition- and model-aware result path."""
    return (workspace_root(out_dir) / "missalignment" / "results"
            / condition / profile / refinement_model)


def export_dir(out_dir: Path, condition: str, refinement_model: str) -> Path:
    return workspace_root(out_dir) / "export" / f"{condition}__{refinement_model}"


def sha256_of(path: Path) -> str | None:
    p = Path(path)
    if not p.is_file():
        return None
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def software_versions() -> dict[str, Any]:
    out: dict[str, Any] = {"python": sys.version.split()[0], "platform": sys.platform}
    for mod in ("numpy", "torch", "mrcfile", "warpylib", "torch_projectors", "scipy"):
        try:
            m = __import__(mod)
            out[mod] = getattr(m, "__version__", "unknown")
        except Exception:
            out[mod] = None
    # IMOD
    imod = None
    for d in (os.environ.get("IMOD_DIR"), "/Applications/IMOD"):
        if d and (Path(d) / "VERSION").is_file():
            imod = (Path(d) / "VERSION").read_text().strip()
            break
    out["imod"] = imod
    return out


def write_manifest(out_dir: Path, settings: dict[str, Any], resolved: dict[str, Any]) -> tuple[Path, Path]:
    """Write the user-editable TOML echo and the fully-resolved JSON manifest."""
    root = create_workspace(out_dir)
    manifest = {
        "schema_version": 1,
        "settings": settings,
        "resolved": resolved,
        "software_versions": software_versions(),
    }
    json_path = root / "project_manifest.json"
    json_path.write_text(json.dumps(manifest, indent=2, sort_keys=True, default=str) + "\n")
    # A minimal TOML echo (the canonical editable copy lives at config/).
    toml_path = root / "project_manifest.toml"
    toml_path.write_text(_render_toml(settings))
    return toml_path, json_path


def _render_toml(settings: dict[str, Any]) -> str:
    lines = ["# Echo of resolved project settings (edit config/project_settings.toml instead).\n"]
    for section, body in settings.items():
        if isinstance(body, dict):
            lines.append(f"[{section}]")
            for k, v in body.items():
                lines.append(f"{k} = {_toml_value(v)}")
            lines.append("")
    return "\n".join(lines) + "\n"


def _toml_value(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_toml_value(x) for x in v) + "]"
    return '"' + str(v).replace('"', '\\"') + '"'


RECON_README = """\
Reconstruction inputs generated by export_warp_to_imod.py
=========================================================
These files apply the exported transform to the *raw* tilt stack to produce a
newly-aligned stack and (optionally) a reconstruction. They never overwrite the
original IMOD .ali/.rec. The expected SOURCE STACK is the raw/binned tilt stack
named in this directory's manifest, NOT the original .ali.

Run:
    bash run_imod_reconstruction.sh
"""


def reconstruction_script(
    raw_stack: Path,
    xf_path: Path,
    tlt_path: Path,
    out_ali: Path,
    expected_xy: tuple[int, int],
    expected_pixel_A: float,
    n_tilts: int,
    module_mode: str = "auto",
    imod_module: str = "imod",
) -> str:
    q = shlex.quote
    return f"""#!/usr/bin/env bash
set -euo pipefail
# Generated by export_warp_to_imod.py. Uses only local generated files and
# writes NEW output names; never overwrites the source .ali/.rec.

RAW={q(str(raw_stack))}
XF={q(str(xf_path))}
TLT={q(str(tlt_path))}
OUT_ALI={q(str(out_ali))}
EXP_X={expected_xy[0]}
EXP_Y={expected_xy[1]}
EXP_TILTS={n_tilts}

# IMOD module policy
if [ "{module_mode}" != "never" ] && ! command -v newstack >/dev/null 2>&1; then
  if type module >/dev/null 2>&1; then module load {q(imod_module)}; fi
fi
command -v newstack >/dev/null 2>&1 || {{ echo "ERROR: newstack not on PATH" >&2; exit 127; }}

# Validate inputs before running.
xf_rows=$(grep -cve '^[[:space:]]*$' "$XF")
[ "$xf_rows" -eq "$EXP_TILTS" ] || {{ echo "ERROR: XF has $xf_rows rows, expected $EXP_TILTS" >&2; exit 1; }}
tlt_rows=$(grep -cve '^[[:space:]]*$' "$TLT")
[ "$tlt_rows" -eq "$EXP_TILTS" ] || {{ echo "ERROR: TLT has $tlt_rows rows, expected $EXP_TILTS" >&2; exit 1; }}
[ -e "$OUT_ALI" ] && {{ echo "ERROR: refusing to overwrite existing $OUT_ALI" >&2; exit 1; }}

newstack -input "$RAW" -output "$OUT_ALI" -xform "$XF" -size "${{EXP_X}},${{EXP_Y}}" -mode 2
echo "Wrote aligned stack: $OUT_ALI (expected ${{EXP_X}}x${{EXP_Y}}, {expected_pixel_A} A/px, $EXP_TILTS tilts)"
echo "Run 'tilt' with your local tilt.missalign.com to reconstruct if desired."
"""
